name: Run Proxy GO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Proxy Server
        run: go run proxy.go -p 1080 -f 22
