name: Run Go Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

jobs:
  run-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'  # Ganti dengan versi Go yang digunakan

      - name: Install Dependencies
        run: go mod tidy  # Pastikan semua dependency diunduh

      - name: Run Proxy
        run: go run proxy.go
